clear all
close all

dir = ('F:\実験データ\本実験\subB\subB(ERD推移等)'); %フォルダ識別
data_mat = 'subB_hist';
load([dir,'\',data_mat]); %データ読み取り

h1=figure;
subplot(3,3,1)
histogram(minimum1,'BinWidth',200,'Normalization','probability')
title('ジャンプなし条件 前半','FontSize',18)
set(gca,'FontSize',18)
xlabel('Time [ms]')
ylabel('Frequency')
xlim([0 4000])
ylim([0 1])

subplot(3,3,4)
histogram(minimum2,'BinWidth',200,'Normalization','probability')
title('ジャンプなし条件 後半','FontSize',18)
set(gca,'FontSize',18)
xlabel('Time [ms]')
ylabel('Frequency')
xlim([0 4000])
ylim([0 1])

subplot(3,3,7)
histogram(minimum12,'BinWidth',200,'Normalization','probability')
title('ジャンプなし条件 合計','FontSize',18)
set(gca,'FontSize',18)
xlabel('Time [ms]')
ylabel('Frequency')
xlim([0 4000])
ylim([0 1])

subplot(3,3,2)
histogram(minimum3,'BinWidth',200,'Normalization','probability')
title('小ジャンプ条件 前半','FontSize',18)
set(gca,'FontSize',18)
xlabel('Time [ms]')
ylabel('Frequency')
xlim([0 4000])
ylim([0 1])

subplot(3,3,5)
histogram(minimum4,'BinWidth',200,'Normalization','probability')
title('小ジャンプ条件 後半','FontSize',18)
set(gca,'FontSize',18)
xlabel('Time [ms]')
ylabel('Frequency')
xlim([0 4000])
ylim([0 1])

subplot(3,3,8)
histogram(minimum34,'BinWidth',200,'Normalization','probability')
title('小ジャンプ条件 合計','FontSize',18)
set(gca,'FontSize',18)
xlabel('Time [ms]')
ylabel('Frequency')
xlim([0 4000])
ylim([0 1])

subplot(3,3,3)
histogram(minimum5,'BinWidth',200,'Normalization','probability')
title('大ジャンプ条件 前半','FontSize',18)
set(gca,'FontSize',18)
xlabel('Time [ms]')
ylabel('Frequency')
xlim([0 4000])
ylim([0 1])

subplot(3,3,6)
histogram(minimum6,'BinWidth',200,'Normalization','probability')
title('大ジャンプ条件 後半','FontSize',18)
set(gca,'FontSize',18)
xlabel('Time [ms]')
ylabel('Frequency')
xlim([0 4000])
ylim([0 1])

subplot(3,3,9)
histogram(minimum56,'BinWidth',200,'Normalization','probability')
title('大ジャンプ条件 合計','FontSize',18)
set(gca,'FontSize',18)
xlabel('Time [ms]')
ylabel('Frequency')
xlim([0 4000])
ylim([0 1])

set(h1,'Units','Inches');
pos=get(h1,'Position');
set(h1,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])

h2=figure;
subplot(3,3,1)
histogram(diff1,'BinWidth',5,'Normalization','probability','FaceColor','r')
title('ジャンプなし条件 前半','FontSize',18)
set(gca,'FontSize',18)
xlabel('Δp,%')
ylabel('Frequency')
xlim([0 200])
ylim([0 1])

subplot(3,3,4)
histogram(diff2,'BinWidth',5,'Normalization','probability','FaceColor','r')
title('ジャンプなし条件 後半','FontSize',18)
set(gca,'FontSize',18)
xlabel('Δp,%')
ylabel('Frequency')
xlim([0 200])
ylim([0 1])

subplot(3,3,7)
histogram(diff12,'BinWidth',5,'Normalization','probability','FaceColor','r')
title('ジャンプなし条件 合計','FontSize',18)
set(gca,'FontSize',18)
xlabel('Δp,%')
ylabel('Frequency')
xlim([0 200])
ylim([0 1])

subplot(3,3,2)
histogram(diff3,'BinWidth',5,'Normalization','probability','FaceColor','r')
title('小ジャンプ条件 前半','FontSize',18)
set(gca,'FontSize',18)
xlabel('Δp,%')
ylabel('Frequency')
xlim([0 200])
ylim([0 1])

subplot(3,3,5)
histogram(diff4,'BinWidth',5,'Normalization','probability','FaceColor','r')
title('小ジャンプ条件 後半','FontSize',18)
set(gca,'FontSize',18)
xlabel('Δp,%')
ylabel('Frequency')
xlim([0 200])
ylim([0 1])

subplot(3,3,8)
histogram(diff34,'BinWidth',5,'Normalization','probability','FaceColor','r')
title('小ジャンプ条件 合計','FontSize',18)
set(gca,'FontSize',18)
xlabel('Δp,%')
ylabel('Frequency')
xlim([0 200])
ylim([0 1])

subplot(3,3,3)
histogram(diff5,'BinWidth',5,'Normalization','probability','FaceColor','r')
title('大ジャンプ条件 前半','FontSize',18)
set(gca,'FontSize',18)
xlabel('Δp,%')
ylabel('Frequency')
xlim([0 200])
ylim([0 1])

subplot(3,3,6)
histogram(diff6,'BinWidth',5,'Normalization','probability','FaceColor','r')
title('大ジャンプ条件 後半','FontSize',18)
set(gca,'FontSize',18)
xlabel('Δp,%')
ylabel('Frequency')
xlim([0 200])
ylim([0 1])

subplot(3,3,9)
histogram(diff56,'BinWidth',5,'Normalization','probability','FaceColor','r')
title('大ジャンプ条件 合計','FontSize',18)
set(gca,'FontSize',18)
xlabel('Δp,%')
ylabel('Frequency')
xlim([0 200])
ylim([0 1])

set(h2,'Units','Inches');
pos=get(h2,'Position');
set(h2,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])